#!/usr/bin/env ruby

require 'mcollective'

include MCollective::RPC

$0 = "mc-pgrep"

ps = rpcclient("process")

if ARGV.length > 0
    pattern = ARGV.shift
else
    pattern = "."
end

ps.list(:pattern => pattern).each do |result|
    puts "%-20s  %5s  %5s  %s" % ["HOST", "USER", "PID", "COMMAND"]
    result[:data][:pslist].each do |proc|
        puts "%-20s  %5s  %5d  %s" % [result[:sender][0,20], proc[:username][0,5], proc[:pid], proc[:cmdline][0,50] ] if proc[:cmdline].match pattern
    end
end

printrpcstats

# vi:tabstop=4:expandtab:ai

